add avatar
js-tasks-ru/htmlcss-20220811_istomina-asia pull request #15
Opened 2022-08-30 15:36 UTC by ase444ka

2022-08-30 15:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-30 16:54 UTC, GSemikozov requested changes

2022-08-30 16:54 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__wrapper {
можно обойтись без этого элемента, а border-radius: 50%; указать сразу на картинке)

2022-09-02 18:47 UTC, ase444ka commented on 06-lection4/01-avatar/avatar.css
> +.avatar__wrapper {
поменяла

2022-09-02 19:46 UTC, GSemikozov approved these changes, later dismissed

2022-09-02 19:46 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-09-04 07:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-04 08:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-05 15:20 UTC, GSemikozov approved these changes

2022-09-05 15:20 UTC, merged