add input
js-tasks-ru/htmlcss-20220811_istomina-asia pull request #23
Opened 2022-09-04 16:33 UTC by ase444ka

2022-09-04 16:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-05 15:34 UTC, GSemikozov requested changes

2022-09-05 15:34 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <label for="input" class="input">
а вот в случае с таким блоком весь контент заворачивать в label не надо )

2022-09-05 15:34 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            Default
вот этот текст - и есть label

2022-09-05 15:34 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    margin-top: 5px;
отступ нужен label, поскольку это опциональный элемент, его может и не быть, а вот инпут - будет всегда)

2022-09-05 15:34 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input_state_error input, .input_state_error input:focus {
селекторы тегов не используем, здесь и ниже должен быть класс

2022-09-05 15:34 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    display: block;
если здесь block, тогда у .input::after none?

2022-09-10 08:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-10 10:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-10 13:31 UTC, ase444ka commented on 07-lection5/04-input/index.html
> +        <label for="input" class="input">
label отделила

2022-09-10 13:32 UTC, ase444ka commented on 07-lection5/04-input/index.html
> +            Default
ага

2022-09-10 13:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-10 13:32 UTC, ase444ka commented on 07-lection5/04-input/input.css
> +    margin-top: 5px;
добавила отступ и дисплэй инлайн-блок

2022-09-10 13:33 UTC, ase444ka commented on 07-lection5/04-input/input.css
> +.input_state_error input, .input_state_error input:focus {
сделала класс. теперь у меня модификатор _state висит на самом блоке и на инпуте тоже, только так инпуту добавляются цветные бордеры

2022-09-10 13:34 UTC, ase444ka commented on 07-lection5/04-input/input.css
> +    display: block;
намек поняла :)) убрала display: block :)

2022-09-13 22:43 UTC, GSemikozov requested changes

2022-09-13 22:43 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    font-style: normal;
в данном случае стили текста лучше сразу задавать на нужном элементе - элементы ведь разные, лишние наследования не нужны)

2022-09-13 22:43 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__input {
инпут лучше завернуть в дополнительный враппер и уже через него ставить нужную иконку

2022-09-13 22:43 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input_state_error::after {
по поводу иконки см выше

2022-09-13 22:43 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__input_state_error, .input__input_state_error:focus {
.input__input_state_error - такие модификаторы лишние, у нас уже есть общий .input_state_error, соответственно можно так: .input_state_error .input__input {}

2022-09-14 06:25 UTC, ase444ka commented on 07-lection5/04-input/input.css
> +    font-style: normal;
исправила

2022-09-14 06:34 UTC, ase444ka commented on 07-lection5/04-input/input.css
> +.input__input_state_error, .input__input_state_error:focus {
переделала

2022-09-14 06:34 UTC, ase444ka commented on 07-lection5/04-input/input.css
> +.input__input {
враппер добавила

2022-09-14 21:11 UTC, GSemikozov requested changes

2022-09-14 21:11 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__wrapper::after {
если задать .input__wrapper position: relative, то тогда высота будет соответствовать высоте инпута, а значит и иконку позиционировать можно будет только относительно инпута, а не всего блока в целом с учетом лейбла (это по поводу top: 40px;)

2022-09-16 20:29 UTC, GSemikozov approved these changes

2022-09-16 20:29 UTC, merged