add main-page
js-tasks-ru/htmlcss-20220811_istomina-asia pull request #3
Opened 2022-08-16 20:13 UTC by ase444ka

2022-08-18 07:48 UTC, GSemikozov requested changes

2022-08-18 07:48 UTC, GSemikozov commented on components/page/page.css
> +.header {
header + footer + main - это отдельные блоки, их надо вынести отсюда и оформить соответствующим образом в папке components

2022-08-18 07:48 UTC, GSemikozov commented on components/page/page.css
> +    padding: 20px 30vw;
vw тут явно лишнее)

2022-08-18 07:48 UTC, GSemikozov commented on components/page/page.css
> +.title_size_3 {
модификатор по типу _1 / _2 / _3 не очень информативен, лучше например _large / _medium

2022-08-23 12:39 UTC, GSemikozov requested changes

2022-08-23 12:39 UTC, GSemikozov commented on components/page/page.css
> +.title {
.title - это уже другой блок, не имеющий отношения к .page. Или все-таки имеет?)

2022-08-23 12:39 UTC, GSemikozov commented on components/page/page.css
> +.title_size_small {
и модификатор тоже

2022-08-23 13:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-23 13:43 UTC, ase444ka commented on components/page/page.css
> +.title {
ну да, точно :) создала отдельный блок title и примиксовала его к page и к хэдеру и к футеру и к карточкам

2022-08-23 13:43 UTC, ase444ka commented on components/page/page.css
> +.title_size_small {
да. его добавила в блок title

2022-08-23 13:58 UTC, GSemikozov approved these changes

2022-08-23 13:58 UTC, merged